// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 35.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'from_color';

  static const String assets_icon_png = 'assets/icon.png';
  static const String from_color$assets_icon_png = 'packages/from_color/assets/icon.png';

  static const String assets_images_body_boulzon_PNG = 'assets/images/body_boulzon.PNG';
  static const String from_color$assets_images_body_boulzon_PNG = 'packages/from_color/assets/images/body_boulzon.PNG';

  static const String assets_images_bottoms_skiny_color_PNG = 'assets/images/bottoms_skiny_color.PNG';
  static const String from_color$assets_images_bottoms_skiny_color_PNG = 'packages/from_color/assets/images/bottoms_skiny_color.PNG';

  static const String assets_images_bottoms_skiny_outline_PNG = 'assets/images/bottoms_skiny_outline.PNG';
  static const String from_color$assets_images_bottoms_skiny_outline_PNG = 'packages/from_color/assets/images/bottoms_skiny_outline.PNG';

  static const String assets_images_image_failed_png = 'assets/images/image_failed.png';
  static const String from_color$assets_images_image_failed_png = 'packages/from_color/assets/images/image_failed.png';

  static const String assets_images_inner_boulzon_color_PNG = 'assets/images/inner_boulzon_color.PNG';
  static const String from_color$assets_images_inner_boulzon_color_PNG = 'packages/from_color/assets/images/inner_boulzon_color.PNG';

  static const String assets_images_inner_boulzon_outline_PNG = 'assets/images/inner_boulzon_outline.PNG';
  static const String from_color$assets_images_inner_boulzon_outline_PNG = 'packages/from_color/assets/images/inner_boulzon_outline.PNG';

  static const String assets_images_outer_blouzon_color_PNG = 'assets/images/outer_blouzon_color.PNG';
  static const String from_color$assets_images_outer_blouzon_color_PNG = 'packages/from_color/assets/images/outer_blouzon_color.PNG';

  static const String assets_images_outer_blouzon_outline_PNG = 'assets/images/outer_blouzon_outline.PNG';
  static const String from_color$assets_images_outer_blouzon_outline_PNG = 'packages/from_color/assets/images/outer_blouzon_outline.PNG';

  static const String assets_images_outer_blouzon_outline_wo_light_PNG = 'assets/images/outer_blouzon_outline_wo_light.PNG';
  static const String from_color$assets_images_outer_blouzon_outline_wo_light_PNG = 'packages/from_color/assets/images/outer_blouzon_outline_wo_light.PNG';

  static const String assets_images_sample_blouzon_jpg = 'assets/images/sample_blouzon.jpg';
  static const String from_color$assets_images_sample_blouzon_jpg = 'packages/from_color/assets/images/sample_blouzon.jpg';

  static const String assets_images_sample_bottoms_jpg = 'assets/images/sample_bottoms.jpg';
  static const String from_color$assets_images_sample_bottoms_jpg = 'packages/from_color/assets/images/sample_bottoms.jpg';

  static const String assets_images_sample_shoes_jpg = 'assets/images/sample_shoes.jpg';
  static const String from_color$assets_images_sample_shoes_jpg = 'packages/from_color/assets/images/sample_shoes.jpg';

  static const String assets_images_sample_tops_jpg = 'assets/images/sample_tops.jpg';
  static const String from_color$assets_images_sample_tops_jpg = 'packages/from_color/assets/images/sample_tops.jpg';

  static const String assets_images_shoes_canvas_color_PNG = 'assets/images/shoes_canvas_color.PNG';
  static const String from_color$assets_images_shoes_canvas_color_PNG = 'packages/from_color/assets/images/shoes_canvas_color.PNG';

  static const String assets_images_shoes_canvas_outline_PNG = 'assets/images/shoes_canvas_outline.PNG';
  static const String from_color$assets_images_shoes_canvas_outline_PNG = 'packages/from_color/assets/images/shoes_canvas_outline.PNG';

  static const String assets_images_tutorial_closet_screen_png = 'assets/images/tutorial/closet_screen.png';
  static const String from_color$assets_images_tutorial_closet_screen_png = 'packages/from_color/assets/images/tutorial/closet_screen.png';

  static const String assets_images_tutorial_howto_closet_1_png = 'assets/images/tutorial/howto_closet_1.png';
  static const String from_color$assets_images_tutorial_howto_closet_1_png = 'packages/from_color/assets/images/tutorial/howto_closet_1.png';

  static const String assets_images_tutorial_howto_closet_2_png = 'assets/images/tutorial/howto_closet_2.png';
  static const String from_color$assets_images_tutorial_howto_closet_2_png = 'packages/from_color/assets/images/tutorial/howto_closet_2.png';

  static const String assets_images_tutorial_howto_palette_1_png = 'assets/images/tutorial/howto_palette_1.png';
  static const String from_color$assets_images_tutorial_howto_palette_1_png = 'packages/from_color/assets/images/tutorial/howto_palette_1.png';

  static const String assets_images_tutorial_howto_palette_2_png = 'assets/images/tutorial/howto_palette_2.png';
  static const String from_color$assets_images_tutorial_howto_palette_2_png = 'packages/from_color/assets/images/tutorial/howto_palette_2.png';

  static const String assets_images_tutorial_howto_palette_3_png = 'assets/images/tutorial/howto_palette_3.png';
  static const String from_color$assets_images_tutorial_howto_palette_3_png = 'packages/from_color/assets/images/tutorial/howto_palette_3.png';

  static const String assets_images_tutorial_login_screen_png = 'assets/images/tutorial/login_screen.png';
  static const String from_color$assets_images_tutorial_login_screen_png = 'packages/from_color/assets/images/tutorial/login_screen.png';

  static const String assets_images_tutorial_palette_screen_png = 'assets/images/tutorial/palette_screen.png';
  static const String from_color$assets_images_tutorial_palette_screen_png = 'packages/from_color/assets/images/tutorial/palette_screen.png';

  static const String assets_images_tyakko_boy_bottoms_PNG = 'assets/images/tyakko/boy_bottoms.PNG';
  static const String from_color$assets_images_tyakko_boy_bottoms_PNG = 'packages/from_color/assets/images/tyakko/boy_bottoms.PNG';

  static const String assets_images_tyakko_boy_outer_PNG = 'assets/images/tyakko/boy_outer.PNG';
  static const String from_color$assets_images_tyakko_boy_outer_PNG = 'packages/from_color/assets/images/tyakko/boy_outer.PNG';

  static const String assets_images_tyakko_boy_outline_PNG = 'assets/images/tyakko/boy_outline.PNG';
  static const String from_color$assets_images_tyakko_boy_outline_PNG = 'packages/from_color/assets/images/tyakko/boy_outline.PNG';

  static const String assets_images_tyakko_boy_shoes_PNG = 'assets/images/tyakko/boy_shoes.PNG';
  static const String from_color$assets_images_tyakko_boy_shoes_PNG = 'packages/from_color/assets/images/tyakko/boy_shoes.PNG';

  static const String assets_images_tyakko_boy_tops_PNG = 'assets/images/tyakko/boy_tops.PNG';
  static const String from_color$assets_images_tyakko_boy_tops_PNG = 'packages/from_color/assets/images/tyakko/boy_tops.PNG';

  static const String assets_images_tyakko_girl_bottoms_PNG = 'assets/images/tyakko/girl_bottoms.PNG';
  static const String from_color$assets_images_tyakko_girl_bottoms_PNG = 'packages/from_color/assets/images/tyakko/girl_bottoms.PNG';

  static const String assets_images_tyakko_girl_outer_PNG = 'assets/images/tyakko/girl_outer.PNG';
  static const String from_color$assets_images_tyakko_girl_outer_PNG = 'packages/from_color/assets/images/tyakko/girl_outer.PNG';

  static const String assets_images_tyakko_girl_outline_PNG = 'assets/images/tyakko/girl_outline.PNG';
  static const String from_color$assets_images_tyakko_girl_outline_PNG = 'packages/from_color/assets/images/tyakko/girl_outline.PNG';

  static const String assets_images_tyakko_girl_shoes_PNG = 'assets/images/tyakko/girl_shoes.PNG';
  static const String from_color$assets_images_tyakko_girl_shoes_PNG = 'packages/from_color/assets/images/tyakko/girl_shoes.PNG';

  static const String assets_images_tyakko_girl_tops_PNG = 'assets/images/tyakko/girl_tops.PNG';
  static const String from_color$assets_images_tyakko_girl_tops_PNG = 'packages/from_color/assets/images/tyakko/girl_tops.PNG';

  static const String assets_termsOfService_html = 'assets/termsOfService.html';
  static const String from_color$assets_termsOfService_html = 'packages/from_color/assets/termsOfService.html';
}
