// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 14.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'from_color';

  static const String assets_images_body_boulzon_PNG = 'assets/images/body_boulzon.PNG';
  static const String from_color$assets_images_body_boulzon_PNG = 'packages/from_color/assets/images/body_boulzon.PNG';

  static const String assets_images_bottoms_skiny_color_PNG = 'assets/images/bottoms_skiny_color.PNG';
  static const String from_color$assets_images_bottoms_skiny_color_PNG = 'packages/from_color/assets/images/bottoms_skiny_color.PNG';

  static const String assets_images_bottoms_skiny_outline_PNG = 'assets/images/bottoms_skiny_outline.PNG';
  static const String from_color$assets_images_bottoms_skiny_outline_PNG = 'packages/from_color/assets/images/bottoms_skiny_outline.PNG';

  static const String assets_images_inner_boulzon_color_PNG = 'assets/images/inner_boulzon_color.PNG';
  static const String from_color$assets_images_inner_boulzon_color_PNG = 'packages/from_color/assets/images/inner_boulzon_color.PNG';

  static const String assets_images_inner_boulzon_outline_PNG = 'assets/images/inner_boulzon_outline.PNG';
  static const String from_color$assets_images_inner_boulzon_outline_PNG = 'packages/from_color/assets/images/inner_boulzon_outline.PNG';

  static const String assets_images_outer_blouzon_color_PNG = 'assets/images/outer_blouzon_color.PNG';
  static const String from_color$assets_images_outer_blouzon_color_PNG = 'packages/from_color/assets/images/outer_blouzon_color.PNG';

  static const String assets_images_outer_blouzon_outline_PNG = 'assets/images/outer_blouzon_outline.PNG';
  static const String from_color$assets_images_outer_blouzon_outline_PNG = 'packages/from_color/assets/images/outer_blouzon_outline.PNG';

  static const String assets_images_outer_blouzon_outline_wo_light_PNG = 'assets/images/outer_blouzon_outline_wo_light.PNG';
  static const String from_color$assets_images_outer_blouzon_outline_wo_light_PNG = 'packages/from_color/assets/images/outer_blouzon_outline_wo_light.PNG';

  static const String assets_images_sample_blouzon_jpg = 'assets/images/sample_blouzon.jpg';
  static const String from_color$assets_images_sample_blouzon_jpg = 'packages/from_color/assets/images/sample_blouzon.jpg';

  static const String assets_images_sample_bottoms_jpg = 'assets/images/sample_bottoms.jpg';
  static const String from_color$assets_images_sample_bottoms_jpg = 'packages/from_color/assets/images/sample_bottoms.jpg';

  static const String assets_images_sample_shoes_jpg = 'assets/images/sample_shoes.jpg';
  static const String from_color$assets_images_sample_shoes_jpg = 'packages/from_color/assets/images/sample_shoes.jpg';

  static const String assets_images_sample_tops_jpg = 'assets/images/sample_tops.jpg';
  static const String from_color$assets_images_sample_tops_jpg = 'packages/from_color/assets/images/sample_tops.jpg';

  static const String assets_images_shoes_canvas_color_PNG = 'assets/images/shoes_canvas_color.PNG';
  static const String from_color$assets_images_shoes_canvas_color_PNG = 'packages/from_color/assets/images/shoes_canvas_color.PNG';

  static const String assets_images_shoes_canvas_outline_PNG = 'assets/images/shoes_canvas_outline.PNG';
  static const String from_color$assets_images_shoes_canvas_outline_PNG = 'packages/from_color/assets/images/shoes_canvas_outline.PNG';
}
